apiVersion: v1
kind: Service
metadata:
    name: "ids721final-494c"
    labels:
        app: "ids721final-494c"
spec:
    type: LoadBalancer
    ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    selector:
        app: "ids721final-494c"