apiVersion: v1
kind: Service
metadata:
    name: "721final-74be"
    labels:
        app: "721final-74be"
spec:
    type: LoadBalancer
    ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    selector:
        app: "721final-74be"