on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: 721final.azurecr.io
        username: ${{ secrets.acr_721final_username }}
        password: ${{ secrets.acr_721final_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t 721final.azurecr.io/721final:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push 721final.azurecr.io/721final:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_721final_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep 721final | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace 721final`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: 721final
        container-registry-url: 721final.azurecr.io
        container-registry-username: ${{ secrets.acr_721final_username }}
        container-registry-password: ${{ secrets.acr_721final_password }}
        secret-name: 721finaldockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: 721final
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          721final.azurecr.io/721final:${{ github.sha }}
        imagepullsecrets: |
          721finaldockerauth
