on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: ids721final.azurecr.io
        username: ${{ secrets.acr_ids721final_username }}
        password: ${{ secrets.acr_ids721final_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t ids721final.azurecr.io/721final:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push ids721final.azurecr.io/721final:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_721final_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep aks-stroke-deploy | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace aks-stroke-deploy`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: aks-stroke-deploy
        container-registry-url: ids721final.azurecr.io
        container-registry-username: ${{ secrets.acr_ids721final_username }}
        container-registry-password: ${{ secrets.acr_ids721final_password }}
        secret-name: 721finaldockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: aks-stroke-deploy
        manifests: |
          manifests/deployment-2.yml
          manifests/service-2.yml
        images: |
          ids721final.azurecr.io/721final:${{ github.sha }}
        imagepullsecrets: |
          721finaldockerauth
